sqlite:
  :adapter: sqlite
  :dbfile: salesforce.sqlite.db
sqlite3:
  :adapter: sqlite3
  :dbfile: salesforce.sqlite3.db
postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: salesforce_test
  :min_messages: ERROR
mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password:
  :database: salesforce_test